### ISSUE TITLE
guide to quarkchain-web3.js for the web

### ISSUE THREAD

**Issue by kvyb** [QuarkChain/quarkchain-web3.js#8]
Hi, 

I want to use the quarkchain-web3.js to create contracts for ICO projects through a web app. However, I run into a problem when installing it for use in a web app (clientside browser). Once the js is installed, how do I use it with a web app to send user inputs. That is how do I put it all together to be sent to cluster? 

Thanks,
K

**Comment by ninjaahhh** [comment]
hi, if you only want to use it in browser environment, you don't need to use npm. check this [html](https://github.com/QuarkChain/quarkchain-web3.js/blob/master/examples/browser/dapp.html) as an example (note that you should access it through http).

for example, a minimum set up using python3 http server module:
```bash
curl https://raw.githubusercontent.com/QuarkChain/quarkchain-web3.js/master/examples/browser/dapp.html > /tmp/dapp.html
cd /tmp && python3 -m http.server 8080  # then open browser and go to localhost:8080/dapp.html
```

**Comment by kvyb** [comment]
Thank you very much for the clarification. I will try to follow the example!
